<a href="https://colab.research.google.com/github/rjnova/BMES_Hypoxia_Research_Team/blob/main/Data_Preprocessing_LRJV_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np
path = "/Hypoxia gene signatures.xlsx"
signatures = pd.read_excel(path, sheet_name = "S1b")

In [32]:
signatures

,Aprelikova *,Benita *,Beyer *,Boidot Cont. * °,Boidot Cyc. * °,Bosco *,Buffa * °,Chen *,Chi *,Denko *,...,Xia °,Xu * °,Yang 2017 °,Yang 2018 Prostate * °,Yang 2018 Sarcoma * °,Ye *,Zhang 2020 * °,Zhang 2021 *,Zhao °,Zou °
0,204.0,58528.0,8635.0,8379.0,8379.0,4800.0,54443.0,5214.0,51534.0,9066.0,...,3162.0,5054.0,6515.0,3976.0,6515.0,6676.0,55143.0,112399.0,5230.0,2621.0
1,5310.0,6676.0,23596.0,29085.0,8685.0,7035.0,5214.0,1815.0,5536.0,1195.0,...,2821.0,8614.0,9697.0,1316.0,10397.0,5230.0,23590.0,665.0,226.0,93129.0
2,9862.0,8974.0,6515.0,51018.0,1975.0,1951.0,2023.0,5230.0,9052.0,9052.0,...,633.0,8497.0,8974.0,150094.0,665.0,10397.0,23657.0,26118.0,5033.0,2203.0
3,54476.0,54665.0,1301.0,5526.0,4913.0,8685.0,24137.0,2821.0,23376.0,3309.0,...,5230.0,NaN,790.0,3726.0,230.0,665.0,NaN,6515.0,7422.0,7422.0
4,1195.0,5351.0,6676.0,8974.0,7251.0,6617.0,11332.0,230.0,6515.0,9709.0,...,229.0,NaN,2734.0,8553.0,2026.0,8701.0,NaN,123.0,NaN,4597.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
CRISPR_KO_df = pd.read_csv("/BIOGRID-ORCS-SCREEN_1721-2.0.18.screen.tab.txt", sep="\t", header=0, engine="python", na_values="-").rename(columns=lambda c: c.lstrip("#"))

In [ ]:
CRISPR_KO_df = CRISPR_KO_df.rename(columns={"SCORE.1": "p-value score", "SCORE.2": "log2FC"})

In [ ]:
CRISPR_KO_df

,SCREEN_ID,IDENTIFIER_ID,IDENTIFIER_TYPE,OFFICIAL_SYMBOL,ALIASES,ORGANISM_ID,ORGANISM_OFFICIAL,p-value score,log2FC,SCORE.3,SCORE.4,SCORE.5,HIT,SOURCE
0,1721,401647,ENTREZ_GENE,GOLGA7B,C10orf132|C10orf133|bA451M19.3|bA459F3.4,9606,Homo sapiens,0.000002,-3.5855,NaN,NaN,NaN,YES,BioGRID ORCS
1,1721,57522,ENTREZ_GENE,SRGAP1,ARHGAP13|NMTC2|KIAA1304,9606,Homo sapiens,0.000033,-4.3671,NaN,NaN,NaN,YES,BioGRID ORCS
2,1721,219981,ENTREZ_GENE,OR5A2,NaN,9606,Homo sapiens,0.000041,-4.7356,NaN,NaN,NaN,YES,BioGRID ORCS
3,1721,441376,ENTREZ_GENE,AARD,C8orf85|LOC441376,9606,Homo sapiens,0.000067,-4.6923,NaN,NaN,NaN,YES,BioGRID ORCS
4,1721,9601,ENTREZ_GENE,PDIA4,ERP70|ERP72|ERp-72,9606,Homo sapiens,0.000072,-4.8150,NaN,NaN,NaN,YES,BioGRID ORCS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3098,1721,114336,ENTREZ_GENE,CGB2,NaN,9606,Homo sapiens,0.289180,-1.8160,NaN,NaN,NaN,YES,BioGRID ORCS
3099,1721,727866,ENTREZ_GENE,FAM156B,TMEM29B,9606,Homo sapiens,0.295180,-1.5708,NaN,NaN,NaN,YES,BioGRID ORCS
3100,1721,554313,ENTREZ_GENE,HIST2H4B,H4/o,9606,Homo sapiens,0.300090,-2.2730,NaN,NaN,NaN,YES,BioGRID ORCS
3101,1721,55894,ENTREZ_GENE,DEFB103B,BD-3|DEFB-3|DEFB103|DEFB3|HBD-3|HBD3|HBP-3|HBP3,9606,Homo sapiens,0.327710,-1.9948,NaN,NaN,NaN,YES,BioGRID ORCS
3102,1721,474384,ENTREZ_GENE,F8A3,NaN,9606,Homo sapiens,0.331930,-1.5374,NaN,NaN,NaN,YES,BioGRID ORCS

In [33]:
unique_count = CRISPR_KO_df["IDENTIFIER_ID"].nunique()

# list of all unique IDs
unique_genes = CRISPR_KO_df["IDENTIFIER_ID"].unique().tolist()

print("Unique gene count:", unique_count)
print("Unique gene IDs:", unique_genes[:10])  # show first 10

Unique gene count: 3101
Unique gene IDs: ['401647', '57522', '219981', '441376', '9601', '56892', '84926', '51478', '55171', '9218']

In [34]:
rows = signatures.iloc[1:].values.tolist()
flat = signatures.iloc[1:].values.flatten().tolist()
columns_as_lists = {col: signatures[col].iloc[1:].tolist() for col in signatures.columns}

print(columns_as_lists)

{'Aprelikova *': [5310.0, 9862.0, 54476.0, 1195.0, 9052.0, 23034.0, 6050.0, 6617.0, 30846.0, 58528.0, 8504.0, 1112.0, 6676.0, 8839.0, 10362.0, 9697.0, 5214.0, 5315.0, 11186.0, 5526.0, 28951.0, 51109.0, 8974.0, 949.0, 2355.0, 5236.0, 1785.0, 54665.0, 4779.0, 5351.0, 2017.0, 2734.0, 1832.0, 6319.0, 4616.0, 1399.0, 23523.0, 23481.0, 5836.0, 23002.0, 23613.0, 28231.0, 55257.0, 5230.0, 23062.0, 10295.0, 10397.0, 665.0, 2997.0, 10994.0, 85360.0, 2821.0, 5864.0, 10135.0, 857.0, 55744.0, 23081.0, 79665.0, 1845.0, 26118.0, 230.0, 80273.0, 84727.0, 2026.0, 7422.0, 7060.0, 8614.0, 26355.0, 5210.0, 56987.0, 2632.0, 80303.0, 55818.0, 10058.0, 1615.0, 5396.0, 5768.0, 7709.0, 3964.0, 6018.0, 10765.0, 7128.0, 8987.0, 27030.0, 5507.0, 26507.0, 4601.0, 64236.0, 5033.0, 25895.0, 23363.0, 7737.0, 6662.0, 51141.0, 79939.0, 23030.0, 4016.0, 112399.0, 3949.0, 7837.0, 9518.0, 3727.0, 80758.0, 22856.0, 4017.0, 8553.0, 3939.0, 8933.0, 9315.0, 29923.0, 55226.0, 54583.0, 3300.0, 10144.0, 901.0, 55647.0, 8996.0, 26502.0, 354.0, 56950.0, 1944.0, 8497.0, 7851.0, 9686.0, 51316.0, 5066.0, 25816.0, 10318.0, 23138.0, 10957.0, 3486.0, 7436.0, 50808.0, 123.0, 133.0, 9538.0, 54995.0, 10570.0, 60485.0, 5163.0, 5352.0, 10428.0, 26207.0, 55326.0, 9337.0, 8324.0, 10670.0, 3098.0, 27020.0, 8321.0, 10163.0, 54933.0, 8365.0, 6781.0, 3099.0, 8566.0, 79957.0, 3625.0, 1999.0, 55139.0, 55689.0, 10424.0, 8819.0, 10370.0, 23462.0, 5277.0, 4714.0, 1152.0, 5598.0, 10904.0, 2021.0, 56905.0, 762.0, 79850.0, 55720.0, 51129.0, 10263.0, 54541.0, 3516.0, 1942.0, 2353.0, 136.0, 5209.0, 2745.0, 7423.0, 55279.0, 93129.0, 664.0, 79369.0, 284119.0, 6666.0, 4351.0, 1198.0, 79929.0, 55076.0, 51428.0, 54101.0, 84851.0, 3714.0, 7026.0, 677.0, 4137.0, 55893.0, 4501.0, 1978.0, 23036.0, 9361.0, 3201.0, 30001.0, 444.0, 10455.0, 79065.0, 3107.0, 3133.0, 3135.0, 29902.0, 3106.0, 727800.0, 51517.0, 51400.0, 2297.0, 729873.0, 8263.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 'Benita *': [6676.0, 8974.0, 54665.0, 5351.0, 4616.0, 1399.0, 5230.0, 10397.0, 2997.0, 10135.0, 7046.0, 23081.0, 79665.0, 9570.0, 26118.0, 230.0, 2597.0, 4015.0, 2908.0, 8614.0, 26355.0, 55818.0, 4601.0, 7852.0, 5033.0, 51141.0, 23030.0, 5914.0, 8864.0, 23480.0, 3939.0, 29923.0, 5292.0, 51008.0, 22822.0, 26502.0, 7071.0, 6566.0, 467.0, 51762.0, 54541.0, 3516.0, 1942.0, 5223.0, 9943.0, 10209.0, 664.0, 1198.0, 55076.0, 353322.0, 30001.0, 444.0, 9867.0, 7416.0, 51400.0, 4282.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 'Beyer *': [23596.0, 6515.0, 1301.0, 6676.0, 770.0, 5214.0, 5165.0, 6095.0, 10272.0, 8974.0, 771.0, 7145.0, 5351.0, 6452.0, 5230.0, 2259.0, 54985.0, 10295.0, 10397.0, 665.0, 2997.0, 10848.0, 2821.0, 5054.0, 768.0, 5376.0, 230.0, 2026.0, 7422.0, 4015.0, 26355.0, 55186.0, 2632.0, 55818.0, 10058.0, 3964.0, 6018.0, 5129.0, 6513.0, 5325.0, 8987.0, 22936.0, 687.0, 5507.0, 4601.0, 1843.0, 7852.0, 5033.0, 8082.0, 23363.0, 51299.0, 51141.0, 23030.0, 7538.0, 9514.0, 2571.0, 3929.0, 9473.0, 694.0, 4017.0, 8553.0, 29923.0, 2752.0, 27141.0, 11309.0, 10144.0, 3184.0, 2028.0, 55647.0, 8996.0, 9520.0, 9123.0, 5211.0, 6518.0, 1382.0, 8497.0, 7851.0, 57007.0, 23635.0, 83604.0, 7436.0, 92211.0, 133.0, 710.0, 3708.0, 5163.0, 5352.0, 55286.0, 58494.0, 23097.0, 1831.0, 3017.0, 978.0, 6781.0, 715.0, 5900.0, 10158.0, 2634.0, 7039.0, 55139.0, 25976.0, 55689.0, 360.0, 11067.0, 64112.0, 1152.0, 6236.0, 164.0, 8800.0, 79001.0, 51129.0, 4054.0, 54541.0, 1942.0, 3726.0, 3777.0, 2244.0, 5728.0, 10924.0, 30008.0, 23023.0, 144195.0, 1466.0, 664.0, 4351.0, 5187.0, 3119.0, 8334.0, 3226.0, 55076.0, 283768.0, 10581.0, 4582.0, 8519.0, 55893.0, 4501.0, 2057.0, 5104.0, 23036.0, 12.0, 1612.0, 25788.0, 26037.0, 30001.0, 8337.0, 11138.0, 4499.0, 283.0, 1052.0, 642559.0, 645682.0, 10687.0, 6414.0, 6038.0, 723790.0, 100133941.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 'Boidot Cont. * °': [29085.0, 51018.0, 5526.0, 8974.0, 9744.0, 1652.0, 100037417.0, 9978.0, 5230.0, 5713.0, 54985.0, 10397.0, 65263.0, 665.0, 2821.0, 944.0, 7343.0, 3837.0, 26118.0, 6207.0, 7422.0, 26355.0, 5210.0, 11222.0, 9801.0, 55818.0, 10969.0, 4601.0, 27340.0, 5033.0, 4694.0, 51141.0, 468.0, 23008.0, 10197.0, 23480.0, 746.0, 81689.0, 87178.0, 901.0, 23519.0, 8125.0, 81631.0, 6187.0, 8497.0, 10957.0, 226.0, 5163.0, 1105.0, 3361.0, 54865.0, 205.0, 55139.0, 401152.0, 91942.0, 117289.0, 5702.0, 92162.0, 54541.0, 3094.0, 5209.0, 5223.0, 246243.0, 51134.0, 1649.0, 8636.0, 6181.0, 1198.0, 8334.0, 205428.0, 84319.0, 10196.0, 64853.0, 353322.0, 3006.0, 386685.0, 170384.0, 8364.0, 554313.0, 6170.0, 26780.0, 5790.0, 147040.0, 6234.0, 642559.0, 23559.0, 643246.0, 100287932.0, 8335.0, 8359.0, 8366.0, 8358.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 'Boidot Cyc. * °': [8685.0, 1975.0, 4913.0, 7251.0, 8569.0, 2219.0, 64211.0, 3476.0, 332.0, 23430.0, 11018.0, 6634.0, 9978.0, 56853.0, 869.0, 65990.0, 23658.0, 8721.0, 6143.0, 51003.0, 6207.0, 22818.0, 51300.0, 64689.0, 3196.0, 54980.0, 81892.0, 51081.0, 6939.0, 81926.0, 54958.0, 7322.0, 746.0, 3351.0, 4005.0, 84298.0, 201292.0, 199964.0, 6391.0, 5202.0, 5546.0, 64645.0, 63875.0, 11267.0, 157848.0, 118881.0, 84191.0, 146713.0, 126259.0, 29901.0, 8290.0, 90204.0, 201255.0, 219409.0, 64979.0, 4761.0, 8433.0, 84839.0, 2787.0, 2940.0, 54998.0, 8636.0, 8334.0, 3768.0, 26576.0, 51286.0, 286256.0, 51079.0, 758.0, 3006.0, 25920.0, 4666.0, 5456.0, 8364.0, 554313.0, 84619.0, 112970.0, 3963.0, 653499.0, 388125.0, 5790.0, 3166.0, 9834.0, 6234.0, 378938.0, 57132.0, 8359.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [35]:
meowwww = set(v for values in columns_as_lists.values() for v in values)
clean = {x for x in meowwww if pd.notna(x)}

print(clean)
print(len(clean))

{131076, 81926.0, 81930.0, 12.0, 16, 163859, 31.0, 36.0, 37, 8233, 43.0, 51.0, 57396, 204851.0, 60.0, 57404, 8263.0, 86.0, 90, 91.0, 90204.0, 114785, 8290.0, 101.0, 8295.0, 114799, 57459.0, 90231.0, 123.0, 8315, 8321.0, 132.0, 133.0, 8324.0, 135.0, 136.0, 8332.0, 8334.0, 8335.0, 8336.0, 8337.0, 57488.0, 123036.0, 8349.0, 159.0, 90271.0, 164.0, 8358.0, 8359.0, 57510.0, 57511, 57515, 8364.0, 8365.0, 8366.0, 57524.0, 182.0, 196, 114884.0, 199.0, 57544, 8394.0, 203.0, 205.0, 8406.0, 114902.0, 8408, 57561.0, 114907, 8412.0, 221.0, 114908.0, 254173.0, 226.0, 57570.0, 229.0, 230.0, 57575.0, 8433.0, 8436.0, 8446, 8450, 268.0, 283.0, 285.0, 286.0, 8490.0, 90410, 254251.0, 301.0, 8493, 57646.0, 8497.0, 308.0, 310.0, 8504.0, 8505.0, 8506.0, 8515.0, 8519.0, 330, 57674.0, 332.0, 139596, 334.0, 57679.0, 147798, 8542.0, 351.0, 57695, 354.0, 8548.0, 358.0, 360.0, 8553.0, 57706.0, 8560.0, 372, 8566.0, 90488, 8569.0, 378, 8573.0, 384, 8577.0, 8578.0, 388.0, 389.0, 390, 394.0, 397.0, 400, 415.0, 8609.0, 57761, 8614.0, 8615, 8624.0, 440, 444.0, 445, 8636.0, 8638, 8639.0, 8644.0, 65990.0, 57799.0, 147920.0, 467.0, 468.0, 8660, 57820, 8674, 483.0, 57826.0, 8677.0, 246243.0, 488.0, 8682, 8685.0, 8690.0, 8698.0, 8701.0, 8702, 8704.0, 90624.0, 8706.0, 115201.0, 516.0, 518.0, 521.0, 522.0, 115209.0, 525.0, 90637, 8721.0, 8722.0, 533.0, 8727, 539.0, 8731, 8740.0, 8743.0, 558.0, 571.0, 8764.0, 8766.0, 586.0, 8780.0, 90701, 593.0, 599.0, 8795.0, 604.0, 8798, 115294, 8800.0, 8801.0, 8805.0, 8818.0, 8819.0, 205428.0, 633.0, 8829.0, 638, 8833.0, 115330.0, 8836.0, 8839.0, 8843.0, 653.0, 8846.0, 661, 662, 664.0, 665.0, 115353.0, 667.0, 8859, 8861.0, 671.0, 8864.0, 675.0, 677.0, 8870.0, 687.0, 90799, 689.0, 694.0, 8887, 8894.0, 49854, 49855, 8898.0, 710.0, 8905.0, 715.0, 8915.0, 8916.0, 115426, 8933.0, 8935.0, 746.0, 90865.0, 754.0, 757, 758.0, 762.0, 90874, 768.0, 770.0, 771.0, 221955, 773.0, 780.0, 8974.0, 729873.0, 790.0, 8987.0, 800.0, 8992.0, 8996.0, 808.0, 811.0, 813, 819.0, 821.0, 9015, 9021.0, 831, 833, 834.0, 58190.0, 9045.0, 9048.0, 857.0, 860.0, 861.0, 9052.0, 868, 869.0, 9063.0, 9069, 541565.0, 901.0, 902.0, 541578, 908.0, 925.0, 928.0, 9123.0, 940.0, 942.0, 944.0, 949.0, 246721.0, 966.0, 574406.0, 969.0, 973.0, 978.0, 9172.0, 9180.0, 989.0, 990, 9181, 9184.0, 9191.0, 1000.0, 1003.0, 9197, 1012.0, 9205, 1022, 9217.0, 1026.0, 1027, 1028.0, 1031.0, 1033.0, 1039.0, 123920.0, 1047, 1051.0, 1052.0, 1054, 9249.0, 1062.0, 353322.0, 9262.0, 222255.0, 9265.0, 1075.0, 9275.0, 9276, 1104.0, 1105.0, 1106, 1112.0, 9314.0, 9315.0, 9319.0, 58477, 58485.0, 9334.0, 9337.0, 58494.0, 9343.0, 1152.0, 9348.0, 9349.0, 58505, 9361.0, 58515, 91283, 9367, 1182, 58528.0, 1186.0, 1195.0, 1196, 1198.0, 9399.0, 1211.0, 25788.0, 1213.0, 9407.0, 9411.0, 115908.0, 25804.0, 1234.0, 25816.0, 25819, 25825.0, 25830.0, 9450.0, 9451, 9452.0, 9456.0, 1266.0, 1268.0, 1278.0, 9473.0, 9474, 9475.0, 1282.0, 1284.0, 1287.0, 1288.0, 1289.0, 1293.0, 1294.0, 1297.0, 25875, 222484, 1301.0, 1314, 1315, 1316.0, 1317, 9507.0, 25895.0, 25897, 9514.0, 25901, 9518.0, 9520.0, 25907.0, 25911.0, 25914.0, 25920.0, 9538.0, 9541, 25927.0, 1353.0, 1356.0, 25932, 25934.0, 9552.0, 25937.0, 1363.0, 9556.0, 9564.0, 9570.0, 116068, 1382.0, 1386.0, 9581, 9588.0, 9590.0, 1399.0, 25976.0, 222584.0, 116092, 1407, 9601, 9612.0, 25998, 1435.0, 1440.0, 9636.0, 26030.0, 9650.0, 1459, 1460.0, 9651.0, 1462.0, 9652.0, 26036, 26037.0, 1466.0, 100287932.0, 9663.0, 26056, 26063.0, 50640, 1490.0, 1491, 9682.0, 9686.0, 9688.0, 9695, 9697.0, 1509.0, 9702, 1515.0, 9709.0, 9710, 83439.0, 1522.0, 83442.0, 1524.0, 83443.0, 9718.0, 1528.0, 83452, 26115.0, 26118.0, 1543.0, 1545.0, 9741.0, 9744.0, 9747.0, 9749.0, 83479, 26136, 50717.0, 9770.0, 26154.0, 91694, 9775.0, 9776, 1592.0, 9790.0, 9792, 1601.0, 1604.0, 9801.0, 124491, 1612.0, 1613.0, 1615.0, 140885.0, 9818, 140890, 9819, 9821, 26207.0, 9834.0, 1644.0, 1647.0, 9839.0, 1649.0, 26227, 1652.0, 1654.0, 50808.0, 386685.0, 9857, 9859.0, 9862.0, 9867.0, 9871, 26258.0, 26260, 83604.0, 116379.0, 26269, 9886.0, 9891.0, 50854, 26286, 9903, 9905.0, 26292.0, 26297.0, 83641, 1728.0, 157378, 386757.0, 1739.0, 9931, 83667, 1748.0, 9943.0, 9950, 100271849.0, 9961.0, 9966.0, 26355.0, 9975, 9976.0, 1785.0, 9978.0, 83707, 9988, 9989.0, 1806.0, 1808.0, 10001.0, 83729.0, 10005.0, 10006, 1815.0, 1824.0, 1825.0, 91942.0, 1831.0, 1832.0, 10025.0, 91947, 1837.0, 1839, 157489.0, 1843.0, 1845.0, 1847, 1848.0, 10040, 51003.0, 51008.0, 51009, 51014, 10058.0, 51018.0, 51026.0, 10072.0, 1890.0, 1901.0, 10096.0, 1906.0, 1907.0, 51062.0, 10105.0, 10106.0, 1915.0, 10112.0, 10113, 10116, 51077.0, 26502.0, 26503, 51079.0, 51081.0, 26507.0, 51083.0, 26511, 1937.0, 1938.0, 10130.0, 10131.0, 10133.0, 1942.0, 10135.0, 1944.0, 51095.0, 51100, 1951.0, 10144.0, 51103.0, 1956.0, 51109.0, 1958.0, 1959.0, 1960.0, 10150, 51110.0, 1964.0, 1965.0, 10158.0, 51118.0, 10163.0, 1974.0, 1975.0, 1977.0, 1978.0, 1979.0, 10171.0, 51129.0, 51130, 1983.0, 51134.0, 10179, 51141.0, 51142.0, 10184, 59339.0, 59340.0, 10189.0, 1999.0, 26576.0, 10193, 10196.0, 10197.0, 2010, 10203.0, 10204.0, 2014.0, 2017.0, 10209.0, 2021.0, 10213.0, 2023.0, 51175.0, 51177.0, 2026.0, 2027.0, 2028.0, 83941.0, 51184.0, 2034, 51192.0, 10237, 51202.0, 92162.0, 2057.0, 2058, 10252, 83982.0, 10263.0, 10272.0, 10279, 10282, 10284.0, 51248.0, 92211.0, 10295.0, 51255, 378938.0, 2114, 51272.0, 10318.0, 2130.0, 51286.0, 10328.0, 2137.0, 84058, 84060.0, 84061.0, 51299.0, 51300.0, 51303, 2152.0, 2155.0, 92270.0, 51312, 51316.0, 2167.0, 10362.0, 2171.0, 26750, 10370.0, 2182.0, 84102, 10376.0, 84105.0, 10380.0, 10381.0, 51348.0, 2199.0, 157848.0, 51351.0, 2202.0, 2203.0, 2204.0, 10397.0, 26780.0, 51361, 84129, 2212.0, 2213.0, 2214.0, 2219.0, 51371.0, 51373.0, 51382.0, 10424.0, 92344, 10428.0, 2237.0, 10434.0, 2244.0, 51397.0, 2246.0, 10439.0, 2248.0, 51398.0, 51400.0, 2252.0, 2256.0, 2259.0, 109504726.0, 10455.0, 2264.0, 10459.0, 2268.0, 51422.0, 84191.0, 2274, 51428.0, 51429, 51430, 92400, 10483, 10484, 2294.0, 10488, 2297.0, 51449.0, 10494.0, 51454.0, 2305.0, 2309.0, 2313.0, 10505.0, 10507.0, 51465, 2317.0, 10509.0, 2321.0, 2330.0, 10524.0, 10525, 2335.0, 84255, 2339, 10535.0, 51495.0, 84263.0, 10540.0, 125228.0, 10544.0, 2353.0, 2354.0, 2355.0, 84272.0, 10549.0, 2359.0, 10551, 51514.0, 10555.0, 51517.0, 84288.0, 10563.0, 51526, 10567, 10570.0, 84298.0, 26959.0, 10576.0, 10581.0, 26973.0, 84319.0, 26984, 51561.0, 26986.0, 10603.0, 10605.0, 51566, 26993, 51569.0, 10615.0, 10616.0, 51585.0, 10628.0, 10632.0, 27018.0, 27020.0, 51599, 10644.0, 27030.0, 27032.0, 10652.0, 51616.0, 10670.0, 10672.0, 51633.0, 51635, 51646, 10687.0, 387521.0, 27074, 92610, 10699.0, 158158, 51668.0, 84441.0, 2523.0, 84447, 10725, 2534, 27109.0, 2537.0, 84458, 2539.0, 2547.0, 133619, 27141.0, 2568.0, 2571.0, 10765.0, 51726, 27153.0, 92689, 2585, 84513, 2597.0, 117289.0, 10797.0, 27181.0, 10802, 51762.0, 84532.0, 133686.0, 10808.0, 2617.0, 2621.0, 2627, 2628.0, 2632.0, 2634.0, 150094.0, 2643, 2644.0, 27230, 10847.0, 10848.0, 2662.0, 2664.0, 10856.0, 27242.0, 2669, 27248, 2673, 133746, 27250.0, 27252.0, 10871.0, 10875.0, 256643, 2697.0, 84617.0, 84619.0, 92815.0, 92822.0, 10903, 10904.0, 2719.0, 10921.0, 10923.0, 10924.0, 2734.0, 27316.0, 10933.0, 2745.0, 2752.0, 84679, 10954, 27338.0, 2764.0, 10956, 10957.0, 10959, 27340.0, 2770.0, 2774.0, 10966.0, 10969.0, 2778.0, 158427, 84701.0, 2783.0, 10975.0, 84706, 2787.0, 2790.0, 10983.0, 2796.0, 10994.0, 2803, 2804, 2805, 84722.0, 84727.0, 2821.0, 11014, 11015, 11018.0, 11030.0, 11040.0, 11045.0, 27434.0, 2869.0, 2870.0, 84790.0, 2872.0, 84792, 11067.0, 84803, 2886, 2887, 11083.0, 723788.0, 117581.0, 723790.0, 2906.0, 2908.0, 11101.0, 2913.0, 84839.0, 2920.0, 2921.0, 2923, 11120, 84851.0, 2937.0, 11130.0, 2940.0, 11138.0, 2950.0, 84876.0, 2959, 11152, 11153, 84883.0, 11157.0, 60313.0, 60314.0, 2975.0, 84901.0, 2987, 11186.0, 2997.0, 11190.0, 3000.0, 3006.0, 84932, 3017.0, 93129.0, 11213.0, 60370, 11221.0, 11222.0, 84950.0, 84951.0, 3036.0, 3037.0, 84958, 11231, 11234, 11237.0, 3048.0, 84981, 3069.0, 11267.0, 3078.0, 100379661.0, 3091.0, 3093.0, 3094.0, 3097.0, 3098.0, 3099.0, 158747, 388125.0, 3105.0, 3106.0, 3107.0, 85027.0, 85028, 11309.0, 3119.0, 3125.0, 100133941.0, 3127.0, 3133.0, 3135.0, 11328.0, 199745.0, 199746, 11332.0, 60485.0, 404550.0, 11335.0, 60489.0, 11346.0, 3155, 3156, 3159.0, 3161.0, 3162.0, 3166.0, 3184.0, 3187.0, 3189.0, 3196.0, 3201.0, 3204.0, 3209.0, 60559, 60561, 3226.0, 339105.0, 60592.0, 3280.0, 3298.0, 3300.0, 3303.0, 3309.0, 3312.0, 3329.0, 3336.0, 3337.0, 60682, 3351.0, 199964.0, 134429.0, 3361.0, 3376.0, 126259.0, 388403, 3382, 85313, 3397.0, 3398.0, 3428.0, 126308.0, 85360.0, 85365, 3475, 3476.0, 3480.0, 3481.0, 85403, 3484.0, 126364.0, 3486.0, 3488.0, 3490.0, 3491.0, 3516.0, 167359, 85464.0, 3552.0, 3556.0, 3557.0, 85480.0, 3569.0, 3572.0, 3576.0, 642559.0, 3604.0, 3613.0, 3621.0, 3622, 3623.0, 3624.0, 3625.0, 3638.0, 3643.0, 28231.0, 28234.0, 3662.0, 3664.0, 3665, 3669.0, 3678.0, 3684.0, 3691.0, 3703, 3708.0, 3709.0, 3714.0, 3716.0, 3725.0, 3726.0, 3727.0, 151195, 3762.0, 3768.0, 100093630, 3777.0, 3812.0, 3837.0, 3838.0, 3843.0, 3855.0, 3858.0, 3866.0, 3872.0, 3895, 3906.0, 3914.0, 3929.0, 3939.0, 3945.0, 3948.0, 3949.0, 3953.0, 3963.0, 3964.0, 3976, 3987.0, 3995, 4004.0, 4005.0, 4015.0, 4016.0, 4017.0, 4035.0, 135112.0, 4054.0, 4055.0, 4060.0, 4064.0, 4069.0, 4071.0, 4076.0, 4077, 4084, 4085.0, 4088.0, 4091.0, 4105.0, 4126, 4137.0, 4141.0, 94274.0, 4163.0, 4170.0, 4171.0, 4189, 118881.0, 4194, 53349, 4205.0, 4207.0, 4210.0, 4224.0, 4233.0, 192669, 643246.0, 4282.0, 200894, 4288.0, 4312.0, 4313.0, 159963.0, 4322.0, 4325.0, 200933.0, 4327.0, 4331.0, 4335, 4350.0, 4351.0, 4355.0, 28951.0, 28962.0, 28966.0, 28974.0, 28985.0, 28989.0, 143684.0, 28998.0, 4430, 4436.0, 4481.0, 4494, 29071.0, 4496.0, 4499.0, 4500.0, 4501.0, 4502.0, 29085.0, 29088.0, 29090.0, 29097.0, 151987, 29110, 29116, 201163.0, 4580.0, 4582.0, 4597.0, 4601.0, 283131, 168451.0, 4616.0, 201255.0, 127534.0, 127544, 4665.0, 4666.0, 4673.0, 53833, 53836.0, 201292.0, 4688.0, 4690, 4694.0, 4698.0, 4708.0, 4709.0, 4712.0, 4713.0, 4714.0, 4719.0, 4720.0, 4726.0, 4728.0, 4731.0, 4739.0, 4747.0, 4758, 4761.0, 4763.0, 53916.0, 53917, 53918, 112267931.0, 160418.0, 4776.0, 4779.0, 4783.0, 4794.0, 4817.0, 4828.0, 4830.0, 144108, 4855.0, 4862.0, 4864, 201475.0, 4869.0, 4881.0, 4893, 4904.0, 100037417.0, 4913.0, 4925, 4929.0, 144195.0, 4946.0, 152404.0, 54101.0, 127845, 4973.0, 112268148, 4982.0, 5007.0, 5031.0, 5033.0, 5034, 5051.0, 5052.0, 5054.0, 54206.0, 54210.0, 5062.0, 5063.0, 152518, 5066.0, 5069.0, 5074.0, 144348.0, 5098.0, 5104.0, 5106, 160760, 5122.0, 5129.0, 5134.0, 619552.0, 5155.0, 5157.0, 5163.0, 5165.0, 5167.0, 5169.0, 5187.0, 29766, 5191.0, 5194.0, 5195.0, 5202.0, 29780.0, 29781.0, 5209.0, 5210.0, 5211.0, 5214.0, 29796.0, 5223.0, 29799.0, 5228.0, 5230.0, 5236.0, 5238, 283768.0, 87178.0, 78987, 5265.0, 78997.0, 5270.0, 5272.0, 79001.0, 79003, 5277.0, 259230.0, 54431, 79009, 201895, 5291.0, 5292.0, 5295.0, 54455, 5306.0, 79035.0, 5310.0, 5311.0, 259266.0, 5315.0, 29896.0, 54476.0, 5325.0, 29901.0, 29902.0, 5328.0, 5329.0, 5336.0, 79065.0, 128218, 79074, 29923.0, 29925.0, 29926.0, 5351.0, 5352.0, 29927, 259307.0, 54512.0, 79091.0, 5365.0, 5366, 79094, 5371.0, 79101, 29950, 5376.0, 54532, 54534.0, 54541.0, 29966.0, 29968, 5396.0, 54554.0, 29980.0, 29982, 29984.0, 5411.0, 79139, 54566.0, 79152.0, 30001.0, 5427.0, 54583.0, 30008.0, 54585, 5435.0, 5440.0, 79174, 554313.0, 5456.0, 5460.0, 5467.0, 5468.0, 54626.0, 5479, 5493.0, 5495.0, 5498.0, 5500.0, 79228, 5504, 5507.0, 284040, 54665.0, 415116, 5520, 54676, 5526.0, 284058, 54682.0, 5536.0, 120224, 5546.0, 54704, 5569.0, 5570.0, 5573.0, 5578.0, 54732, 5590, 284119.0, 5598.0, 5604, 5611, 5625.0, 54778, 5635.0, 79365.0, 79369.0, 161291.0, 54800.0, 54801.0, 54802, 374291.0, 5653.0, 54808, 5660, 54812, 54813, 54832.0, 5686.0, 54839, 5688.0, 5690.0, 5693.0, 54845.0, 5695.0, 5699.0, 5701.0, 5702.0, 5708.0, 54863.0, 5713.0, 5714.0, 5715.0, 54865.0, 54867, 5728.0, 54880.0, 54884, 54885, 5738.0, 374378, 5740.0, 5742.0, 5743.0, 54910.0, 5763.0, 153222, 5768.0, 54928.0, 5777, 5778.0, 54933.0, 153241, 5787.0, 54940.0, 5790.0, 5792.0, 5794, 5798.0, 54951.0, 5800.0, 5801.0, 54953, 5803.0, 54958.0, 54968.0, 5817.0, 54980.0, 5829.0, 54985.0, 5836.0, 54995.0, 54998.0, 79576, 79577, 440026, 55002, 55011.0, 55015, 5864.0, 5868.0, 5876.0, 5879.0, 5880.0, 55033, 55034, 55038.0, 5892.0, 5898.0, 5900.0, 5901.0, 5902.0, 79631, 112399.0, 55062, 284439.0, 5914.0, 79644.0, 55076.0, 5926.0, 79660, 5935.0, 5936.0, 79665.0, 653121, 79682.0, 390980, 55119.0, 79701.0, 55132, 55139.0, 55142.0, 55145, 79723.0, 5996.0, 79725, 5998.0, 55151, 79739, 6013.0, 6016, 6018.0, 79752, 79753, 55180, 55186.0, 6038.0, 55191.0, 6041.0, 79770, 6046, 6050.0, 55204, 55208, 55219, 79801.0, 55226.0, 79818.0, 6095.0, 6100, 55254, 55255, 79832.0, 55257.0, 112611, 55270.0, 6122.0, 55274.0, 79850.0, 55279.0, 6132.0, 55286.0, 6138.0, 6143.0, 6157.0, 55312.0, 6168.0, 6169.0, 6170.0, 55323.0, 6173.0, 55325.0, 6175.0, 55326.0, 6181.0, 6187.0, 6188.0, 284716.0, 55342.0, 6196.0, 79929.0, 6202.0, 55355.0, 79930.0, 6205.0, 6207.0, 55359, 79939.0, 6218.0, 145482.0, 55379.0, 79957.0, 6232.0, 55384.0, 6234.0, 6235.0, 6236.0, 6237.0, 79961.0, 30817.0, 333926.0, 30846.0, 80000.0, 6273.0, 6274.0, 6275.0, 30849.0, 6277.0, 6278.0, 80006.0, 6281.0, 80018.0, 6301, 6303.0, 6307, 6309, 6310.0, 6319.0, 137392.0, 6331.0, 653499.0, 6338.0, 374986.0, 6347.0, 96459, 55505.0, 6364.0, 6374.0, 6382.0, 6385, 6391.0, 375033, 6400, 6414.0, 6415.0, 375056, 219409.0, 137492, 55573.0, 111089941, 22809.0, 22818.0, 22820, 22822.0, 55591.0, 6446.0, 112942, 6451.0, 6452.0, 22836.0, 112950, 55608, 6457.0, 55612.0, 6472.0, 22856.0, 6474.0, 112970.0, 6477, 6478.0, 22861.0, 22863.0, 645455.0, 6482.0, 55634, 22872.0, 55640.0, 80219, 22879, 55647.0, 22882.0, 22890.0, 55664, 6513.0, 6515.0, 55668, 6518.0, 6520, 6525.0, 22911, 63874, 6531.0, 63875.0, 6533.0, 22918.0, 6535.0, 22920, 55689.0, 80267, 6541.0, 22926, 170384.0, 80273.0, 55700.0, 63893.0, 22936.0, 6558.0, 6559.0, 6566.0, 55720.0, 55723.0, 55726, 55727.0, 80303.0, 55729.0, 80307.0, 63929.0, 80315.0, 55741, 55744.0, 80328, 80336, 6612.0, 22998, 55768, 6617.0, 23002.0, 6619, 55773, 23008.0, 6625.0, 23015, 6634.0, 55790.0, 23023.0, 6640.0, 23030.0, 6648.0, 23034.0, 203259, 23036.0, 6653.0, 23037.0, 55805.0, 203260, 113146.0, 6659.0, 6662.0, 6666.0, 55818.0, 6670.0, 6671.0, 55824.0, 6674, 6675, 6676.0, 55829, 23062.0, 23071, 55840, 6695.0, 6696.0, 23080, 23081.0, 55853.0, 6705.0, 55857, 219699, 645682.0, 6709.0, 6710.0, 23093.0, 23097.0, 6715.0, 64061, 55871.0, 6728, 6729.0, 6730, 6731, 6732.0, 23112.0, 55884.0, 64080, 6737.0, 64081.0, 55893.0, 219736.0, 6745, 64089, 6747.0, 113246, 55904, 23138.0, 100506211.0, 55911.0, 55917.0, 64112.0, 6774.0, 23160.0, 6777.0, 64121, 6781.0, 6782, 64127.0, 6789.0, 6790.0, 64135.0, 55957, 23190, 6811, 6814.0, 285343.0, 55968.0, 23204.0, 55974, 121512.0, 23209.0, 23210.0, 6836, 23228.0, 23231.0, 441024.0, 23235.0, 56005, 64211.0, 6868, 23253, 64215, 23256, 23258, 23262.0, 441054.0, 64222.0, 64236.0, 6897, 727800.0, 6921.0, 6934.0, 6935.0, 6936.0, 6939.0, 6941.0, 6945.0, 100506403.0, 23332.0, 80700, 23363.0, 64324.0, 64332, 23376.0, 138065, 6996.0, 219988, 64343, 64344.0, 7004.0, 154467.0, 7015.0, 7022.0, 7026.0, 23410.0, 23411, 56180, 64374, 80758.0, 64376, 80762.0, 7035.0, 7037.0, 7039.0, 7040.0, 7043.0, 7045.0, 7046.0, 23429, 23430.0, 23433, 7050, 23435.0, 220042.0, 80781.0, 7054.0, 23440.0, 7057.0, 7060.0, 7064.0, 7071.0, 7077.0, 23461, 23462.0, 23463.0, 252839.0, 7087.0, 7088.0, 23471, 7090.0, 23480.0, 23481.0, 7110, 56270, 7124.0, 80853, 7128.0, 80856.0, 23515, 23519.0, 23521.0, 23523.0, 23527.0, 7145.0, 56300.0, 7162.0, 7163.0, 23548, 7165.0, 7167.0, 7170.0, 7171.0, 7172.0, 23554.0, 23558, 23559.0, 171017.0, 7178.0, 7181.0, 171023.0, 7184, 7204.0, 23590.0, 23596.0, 23603.0, 220213, 23608, 23613.0, 285761.0, 7251.0, 23635.0, 23642, 23645.0, 23650.0, 23657, 23658.0, 7280.0, 7286, 154743, 7289, 7295.0, 64645.0, 81034.0, 64651, 81035.0, 7314.0, 7318.0, 7321.0, 7322.0, 23705.0, 56477.0, 23710, 154791.0, 7341.0, 162989, 7343.0, 728239.0, 7345.0, 64689.0, 7347, 441531.0, 7360, 23753, 7372.0, 7374.0, 7378, 23764.0, 113878.0, 7385.0, 7388.0, 195814, 64746, 23788.0, 64755.0, 7416.0, 64764.0, 7422.0, 7423.0, 7424.0, 7428.0, 7431.0, 64778.0, 7436.0, 64781.0, 285966.0, 163087, 64786, 146713.0, 7453, 56605, 64798.0, 7456.0, 7466, 7474.0, 7475.0, 130367, 7490.0, 64834.0, 7494, 56650, 56658, 64853.0, 7511.0, 64866.0, 7528.0, 7538.0, 7543.0, 286097.0, 7581.0, 64928.0, 7597.0, 64979.0, 64981.0, 114134.0, 64983.0, 7673, 7692, 56853.0, 7709.0, 65065, 286256.0, 122416.0, 7730.0, 56886, 7737.0, 56892.0, 56900, 24137.0, 56905.0, 24145.0, 360023, 56925.0, 65117, 441951, 147040.0, 56929, 81502.0, 7779.0, 56942.0, 56943.0, 56950.0, 7803.0, 286343, 56967.0, 81555, 56985, 56987.0, 81563.0, 7837.0, 81565, 81567.0, 122525, 81570.0, 81577.0, 7851.0, 7852.0, 57003, 57007.0, 130749.0, 7871.0, 7873.0, 89797.0, 7879.0, 57035, 81631.0, 65263.0, 7922, 286451, 401152.0, 130827, 57103.0, 81689.0, 57121.0, 548645, 7975, 7980.0, 57132.0, 7988, 57140.0, 57142.0, 100302652, 57148.0, 57153.0, 57161.0, 8029.0, 8030, 8061.0, 57214.0, 57221.0, 57222.0, 57223.0, 8082.0, 196500.0, 221079, 196527, 8125.0, 8140.0, 131034.0, 221154.0, 81892.0}
2154

In [37]:
overlap = set(unique_genes) & clean
count_overlap = len(overlap)
print(count_overlap)

0